# Generated by Django 5.2.1 on 2025-05-30 14:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên chỉ số')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã chỉ số')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('unit', models.CharField(max_length=50, verbose_name='Đơn vị tính')),
                ('data_type', models.CharField(choices=[('INTEGER', 'Số nguyên'), ('DECIMAL', 'Số thập phân'), ('PERCENT', 'Phần trăm')], max_length=20, verbose_name='Loại dữ liệu')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ngưỡng mục tiêu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Chỉ số DTI',
                'verbose_name_plural': 'Chỉ số DTI',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('DATA_ENTRY', 'Data Entry'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=50, verbose_name='Vai trò')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đầy đủ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DTIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Giá trị')),
                ('period_date', models.DateField(verbose_name='Ngày kỳ báo cáo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo giá trị')),
                ('entered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người nhập')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dti_dashboard.dtiindex', verbose_name='Chỉ số')),
            ],
            options={
                'verbose_name': 'Giá trị chỉ số DTI',
                'verbose_name_plural': 'Giá trị chỉ số DTI',
                'ordering': ['-period_date', 'index__name'],
                'unique_together': {('index', 'period_date')},
            },
        ),
    ]
